### ISSUE TITLE
Not listing all assets/dividends

### ISSUE THREAD

**Issue by chevdor** [libertyswede/dividend-plugin#1]
Hello,
I am testing 1.01. The plugin only lists 1 transaction for 1 asset and misses many of the other entries.

**Comment by libertyswede** [comment]
What is you NXT address, and what dividend transactions are you missing?

**Comment by chevdor** [comment]
Here is an account that exhibits the problem: NXT-3NTG-FJPG-FFRY-FSZH4

Running the plugin gives me (NRS version is 1.5.12):
Dividend count: 1
Dividend recieved:  42048.85 NXT

Height  Transaction ID  Asset   Shares  Dividend
445136  14778498726668180114    BankRoll    500000      42048.85

If you look at transaction 2942262844098388903 for instance, you will see that it is a dividend transaction and it seems not to be taken into account by your plugin.

I checked out the console output and I get no error/warning coming from the plugin.

**Comment by libertyswede** [comment]
Hi, thank you for your issue report.
This plugin only supports the NXT built in dividend transaction type (type: 2, subtype: 6).

http://www.mynxt.info/transaction/2942262844098388903
The transaction you have reported is a ordinary payment transaction (type: 0, subtype: 0), which will not be shown, at least not in this version.
